import type { CharDef, CharId } from './types';

export const CHARACTERS: Record<CharId, CharDef> = {
  garnet: {
    id: 'garnet',
    name: 'ガーネット',
    reading: 'Garnet',
    species: '獏（夢を喰う獣）',
    hair: '#7b4f9e',
    hairDark: '#4b2f63',
    skin: '#e9d3c6',
    accent: '#e8b44a',
    cloth: '#2b2233',
    hairstyle: 'wave',
    eyestyle: 'sleepy',
    parts: ['horns', 'earring', 'cheeks'],
    intro: 'カフェ・ノクターナルの店主。眠らない街で、いちばん眠らない人。',
  },
  yuki: {
    id: 'yuki',
    name: 'ユキ',
    reading: 'Yuki',
    species: '雪女',
    hair: '#e4ecf7',
    hairDark: '#a8bcd6',
    skin: '#f5f8fc',
    accent: '#8fd3e8',
    cloth: '#2c3e63',
    hairstyle: 'hime',
    eyestyle: 'sleepy',
    parts: ['snow', 'cheeks'],
    intro: '小説を書いている雪女。人に読ませるのが怖い。',
  },
  luca: {
    id: 'luca',
    name: 'ルカ',
    reading: 'Luca',
    species: '人狼',
    hair: '#5c4033',
    hairDark: '#3b281f',
    skin: '#d9a87c',
    accent: '#d1703c',
    cloth: '#33323f',
    hairstyle: 'messy',
    eyestyle: 'sharp',
    parts: ['wolfears', 'wolflake', 'fangs'],
    intro: 'ベース弾きの人狼。夜になると耳が冴えて、眠れない。',
  },
  mira: {
    id: 'mira',
    name: 'ミラ',
    reading: 'Mira',
    species: 'アンドロイド',
    hair: '#bfdcd5',
    hairDark: '#8fb0aa',
    skin: '#ece6df',
    accent: '#67c9bd',
    cloth: '#404a55',
    hairstyle: 'bob',
    eyestyle: 'round',
    parts: ['antenna', 'visor'],
    intro: '味覚を学習中のアンドロイド。「好き」の定義を探している。',
  },
  sera: {
    id: 'sera',
    name: 'セラ',
    reading: 'Sera',
    species: '吸血鬼',
    hair: '#2a1c2e',
    hairDark: '#150f1a',
    skin: '#f0e2e2',
    accent: '#b43350',
    cloth: '#261f30',
    hairstyle: 'long',
    eyestyle: 'sharp',
    parts: ['fangs', 'earring', 'wings'],
    intro: '司法書士の吸血鬼。感情を契約書のように扱う。',
  },
  noa: {
    id: 'noa',
    name: 'ノア',
    reading: 'Noa',
    species: '妖精',
    hair: '#ff9d5c',
    hairDark: '#d66f34',
    skin: '#fbe3cf',
    accent: '#ffd166',
    cloth: '#6fbf7a',
    hairstyle: 'twin',
    eyestyle: 'round',
    parts: ['wings', 'antenna', 'cheeks'],
    intro: '配達屋の妖精。街でいちばん声が大きい。',
  },
  olga: {
    id: 'olga',
    name: 'オルガ',
    reading: 'Olga',
    species: 'ドワーフ',
    hair: '#8c4a2f',
    hairDark: '#5c2f1c',
    skin: '#d8a173',
    accent: '#c9a227',
    cloth: '#463a29',
    hairstyle: 'bun',
    eyestyle: 'sharp',
    parts: ['beard', 'glasses'],
    intro: '時計職人のドワーフ。分厚い手で、髪の毛より細い歯車を扱う。',
  },
  kai: {
    id: 'kai',
    name: 'カイ',
    reading: 'Kai',
    species: '人間（たぶん）',
    hair: '#2f2b33',
    hairDark: '#1b181e',
    skin: '#e6c4a8',
    accent: '#c9a06a',
    cloth: '#2f3540',
    hairstyle: 'short',
    eyestyle: 'round',
    parts: [],
    intro: 'この店に入った、新しいバリスタ。あなた。',
  },
};

export const REGULARS: CharId[] = ['yuki', 'luca', 'mira', 'sera', 'noa', 'olga'];

export const CHAR_ORDER: CharId[] = ['garnet', 'yuki', 'luca', 'mira', 'sera', 'noa', 'olga', 'kai'];