import { profileOrder } from '../ingredients';
import type { Chapter } from '../types';
import {
  chapterCard,
  choice,
  enter,
  exit,
  heart,
  jump,
  nar,
  order,
  say,
  set,
  sfx,
  trustUp,
} from './helpers';

/**
 * 第二章：雨の音
 *   ユキの原稿 → セラ（故郷の味）→ ノア（妖精の配達人）
 */
export const NIGHT2: Chapter = {
  id: 'night2',
  title: '第二章',
  subtitle: '雨の音',
  start: 'n2a',
  scenes: [
    {
      id: 'n2a',
      title: '雨',
      bg: 'street-rain',
      lines: [
        nar('この街の雨は、降り方が三種類ある。'),
        nar('静かに降る雨、うるさい雨、そして、誰かを待っているみたいな雨。'),
        nar('今日は、三番目だった。'),
        nar('店の窓には、街の灯りが、水の膜を通って滲んでいる。'),
        sfx('bell'),
        nar('ベルが鳴る。少しだけ、遠慮がちな音。'),
        enter('yuki', 'center', 'shy'),
        say('yuki', '……こんばんは。', 'shy'),
        say('yuki', 'あの、これ。'),
        nar('彼女は、濡れないように抱えていた紙の束を、カウンターに置いた。'),
        nar('表紙には、手書きで題名が書いてある。'),
        say('yuki', '……短編です。三十二枚。', 'normal'),
        say('yuki', '雪女じゃない話。夜の街の話。'),
        say('yuki', 'わたしのじゃない、誰かの話。'),
        say('yuki', '……だから、読まれるかどうか、こわいんです。', 'tired'),
        sfx('bell'),
        say('yuki', '……あ、お客さん。'),
        say('yuki', 'とりあえず、いつもの、お願いします。'),
        say('yuki', '冷たいの。', 'normal'),
        say('yuki', '……少しだけ、ミルクを入れてくれると、うれしいです。'),
        order({
          order: {
            kind: 'exact',
            id: 'n2-yuki-1',
            label: '「いつもの」——冷たいの、ミルク入り',
            ingredients: ['coffee', 'milk'],
            temperature: 'iced',
          },
          customer: 'yuki',
          hint: 'ユキ：コーヒー＋ミルク／アイス（アイスラテ）。',
          results: { perfect: 'n2b', good: 'n2b', off: 'n2b2' },
        }),
      ],
    },
    {
      id: 'n2b',
      bg: 'cafe-counter',
      lines: [
        nar('彼女は、カップを受け取ると、原稿の束を少しだけ横に押やった。'),
        say('yuki', '……どうぞ。', 'shy'),
        say('yuki', '読んでるあいだ、わたしは、外を見ています。'),
        say('yuki', '目を合わせられないので。', 'shy'),
        jump('n2c'),
      ],
    },
    {
      id: 'n2b2',
      bg: 'cafe-counter',
      lines: [
        say('yuki', '……ありがとう。', 'shy'),
        say('yuki', 'これも、好きですけど……でも、今日は、ちょっと、ちがいます。'),
        say('yuki', '冷たくて、コーヒーで、ミルクが入ってるの。', 'normal'),
        say('yuki', '雪の日に、窓が白くなるみたいなやつ。'),
        nar('彼女は、原稿を抱えたまま、カップの縁に口をつけた。'),
        jump('n2c'),
      ],
    },
    {
      id: 'n2c',
      bg: 'cafe-window',
      lines: [
        nar('雨足が強くなる。窓が、細かく震えている。'),
        nar('その音が、消えた。'),
        nar('扉が開いたからではなく、開いた扉の向こうに、いちばん冷たい空気が立っていたからだ。'),
        enter('sera', 'right', 'smug'),
        say('sera', '……この雨は、傘を持っていない者にだけ、意地悪ですね。', 'smug'),
        say('sera', '私は傘を持っているが、ささないことにしている者です。'),
        say('sera', 'セラ。職業は、司法書士。', 'normal'),
        say('sera', '夜に働いているのは、書類仕事の大半が、昼には眩しすぎるからです。', 'smug'),
        nar('外套を脱ぐと、店内のランプが、彼女の背中で二つに折れた影を作った。'),
        heart('（羽がある、と思った。けれど、もう見えない。）'),
        say('sera', '店主さん、いつもの', 'normal'),
        say('sera', '……ああ、いたのか。新人。', 'smug'),
        say('sera', 'では、あなたに頼みましょうか。'),
        say('sera', '故郷の味、というものを出してください。', 'smug'),
        heart('（いきなり、いちばん難しいやつだ。）'),
        say('sera', '羊水と同じ暗さの山の中で、祖母が淹れていたものが、あります。'),
        say('sera', '茶葉は、保存状態の悪い紅茶。', 'normal'),
        say('sera', '酸っぱいものが、ひと切れ。'),
        say('sera', '甘いものが、ひとさじ。'),
        say('sera', '雪の降る前に、その匂いが、村中に広がるんです。', 'tired'),
        say('sera', '……ふ。若いバリスタには、抽象語が多すぎましたか。', 'smug'),
        order({
          order: {
            kind: 'exact',
            id: 'n2-sera-1',
            label: '故郷の味',
            ingredients: ['tea', 'lemon', 'honey'],
            temperature: 'hot',
          },
          customer: 'sera',
          hint: 'セラ：紅茶＋レモン＋はちみつ／温かい。山の紅茶。',
          results: { perfect: 'n2d', good: 'n2d', off: 'n2d2' },
        }),
      ],
    },
    {
      id: 'n2d',
      bg: 'cafe-counter',
      lines: [
        nar('カップを置くと、セラは、しばらく何も言わなかった。'),
        nar('言わない時間が、とても長かった。'),
        say('sera', '……契約書には、こんな条項は書けませんね。', 'normal'),
        say('sera', '「故郷の味」の履行方法は、条文では、定義できない。'),
        say('sera', 'だから、私は、ずっと、これを探していたのかもしれません。', 'tired'),
        nar('彼女は、カップを両手で、ゆっくりと抱えた。'),
        nar('寒いものを抱える、というより、抱え方を忘れた人の動作だった。'),
        say('sera', '祖母は、村で、いちばん遅くまで起きている人でした。'),
        say('sera', '私は、眠らない子でしたから、よく、その背中を見ていました。'),
        say('sera', '……吸血鬼の子というのは、そういうもので。'),
        say('sera', '今でも、夜は、いちばん、静かな場所です。', 'normal'),
        set((s) => {
          s.flags.sera_home = true;
          s.trust.sera = (s.trust.sera ?? 0) + 2;
        }),
        jump('n2e'),
      ],
    },
    {
      id: 'n2d2',
      bg: 'cafe-counter',
      lines: [
        nar('セラは、一口だけ飲んで、カップを置いた。'),
        say('sera', '……うーん。惜しい。', 'smug'),
        say('sera', '私が言ったことを、もう一度、条文のように読んでください。'),
        say('sera', '「保存状態の悪い紅茶」。つまり、渋みより、香りの記憶。', 'normal'),
        say('sera', '「酸っぱいものがひと切れ」——果物の酸。'),
        say('sera', '「甘いものがひとさじ」——砂糖ではない、蜜。', 'smug'),
        say('sera', '……次は、できるでしょう。', 'normal'),
        trustUp('sera', 1),
        jump('n2e'),
      ],
    },
    {
      id: 'n2e',
      bg: 'cafe-night',
      lines: [
        nar('扉が、乱暴に開いた。'),
        nar('雨が、床にまで入ってくる。'),
        exit('yuki'),
        enter('noa', 'center', 'happy'),
        say('noa', 'ぬれてるの! 配達なの! とどけたの!', 'happy'),
        say('noa', 'えらいから、あまいのみたい!', 'happy'),
        say('noa', '店長〜、こんばんも元気!'),
        nar('妖精だった。背中に、透けた翅が二枚。'),
        nar('手には、びしょ濡れの封筒が一通。'),
        say('noa', 'あっ。', 'surprise'),
        say('noa', 'セラさん! いた!'),
        nar('ノアは、封筒をセラに差し出した。'),
        nar('宛名は、手書きの、古い字だった。'),
        say('sera', '……これは。', 'surprise'),
        say('sera', '私の村から、ですか。', 'normal'),
        say('noa', 'うん! 山の上から! 三日かかった!'),
        say('noa', 'かいてる人は、えーと、老いた人! すごく老いた人!'),
        say('sera', '……そう。', 'tired'),
        nar('セラは、封筒を受け取って、しばらく、その表を見ていた。'),
        nar('開けなかった。けれど、外套の内側に、静かにしまった。'),
        say('sera', '……バリスタ。', 'normal'),
        say('sera', 'この店の客は、妙な縁を、運んでくるんですね。', 'smile'),
        exit('sera'),
        say('noa', 'あれ? セラさん、帰っちゃった。'),
        say('noa', 'わたし、あまいの! まだ飲んでない!', 'angry'),
        say('noa', 'あったかいので、すごくあまいやつ!'),
        order({
          order: profileOrder({
            id: 'n2-noa-1',
            label: 'すごく甘くて、あったかくて、まろやかなもの',
            from: ['chocolate', 'milk', 'honey'],
            temperature: 'hot',
          }),
          customer: 'noa',
          hint: 'ノア：とにかく甘い。チョコ＋ミルク＋はちみつあたり。',
          results: { perfect: 'n2f', good: 'n2f', off: 'n2f' },
        }),
      ],
    },
    {
      id: 'n2f',
      bg: 'cafe-night',
      lines: [
        nar('ノアは、大きな音を立てて、すごい勢いで飲んだ。'),
        say('noa', 'あまい! あったかい! しぬかと思った!', 'happy'),
        say('noa', '配達は、雨のときがいちばん、うれしいんだ。'),
        say('noa', 'だって、手紙は、びしょぬれになったら困るでしょ。'),
        say('noa', 'だから、走る。走ると、体があったかくなる。', 'happy'),
        say('noa', 'で、ここに来ると、あまいのが飲める!'),
        say('noa', '世界、できてる!', 'happy'),
        heart('（この人は、たぶん、この店でいちばん、眠れている。）'),
        say('noa', 'そういえば、手紙の中身って、なんだろうね。', 'think'),
        say('noa', 'セラさん、うれしそうだった?', 'normal'),
        say('noa', '……うれしそう、だったよ。たぶん。', 'smile'),
        exit('noa'),
        jump('n2g'),
      ],
    },
    {
      id: 'n2g',
      title: '原稿',
      bg: 'cafe-dawn',
      lines: [
        nar('夜が、終わりに近づいている。'),
        nar('ユキはまだ、窓の外を見ていた。原稿は、カウンターの上に置いたまま。'),
        enter('yuki', 'center', 'tired'),
        say('yuki', '……あの。', 'shy'),
        say('yuki', '読むの、まだ、決めてなくて。'),
        choice(
          [
            {
              text: 'いま読む（原稿を開く）',
              set: (s) => {
                s.flags.read_yuki = true;
                s.trust.yuki = (s.trust.yuki ?? 0) + 2;
              },
              to: 'n2h',
            },
            {
              text: '「今夜は、預かっておきます」',
              set: (s) => {
                s.flags.keep_yuki = true;
                s.trust.yuki = (s.trust.yuki ?? 0) + 1;
              },
              to: 'n2h2',
            },
            {
              text: '「口で聴きたい。あらすじだけ」',
              set: (s) => {
                s.flags.tell_yuki = true;
                s.trust.yuki = (s.trust.yuki ?? 0) + 2;
              },
              to: 'n2h3',
            },
          ],
          'どうする?',
        ),
      ],
    },
    {
      id: 'n2h',
      bg: 'cafe-dawn',
      lines: [
        nar('一枚目をめくる。'),
        nar('雪の降らない街の話だった。'),
        nar('眠れない女が、深夜のコンビニに行く。'),
        nar('そこで、同じように眠れない誰かと、缶コーヒーを分ける。'),
        nar('それだけの話。'),
        nar('なのに、最後の一行で、あたたかいものが、喉の奥に残った。'),
        heart('（うまい、とかではなく。'),
        heart('（この人は、眠れない人たちの形を、ちゃんと知っている。'),
        say('yuki', '……顔、見ないでください。', 'shy'),
        say('yuki', 'いま、たぶん、ひどい顔なので。'),
        say('yuki', '……ありがとう。読むの、はやいですね。'),
        say('yuki', '最後の一行、書き直したんです。七回くらい。', 'normal'),
        say('yuki', '……また、持ってきます。もっと、ちゃんとしたの。'),
        jump('n2i'),
      ],
    },
    {
      id: 'n2h2',
      bg: 'cafe-dawn',
      lines: [
        nar('原稿は、カウンターの引き出しに、濡れないように入れた。'),
        say('yuki', '……いいんですか。', 'normal'),
        say('yuki', '店のもの、みたいに。'),
        say('yuki', '……じゃあ、次に来たときに、読んでください。', 'shy'),
        say('yuki', 'そのつもりで、いるので。'),
        jump('n2i'),
      ],
    },
    {
      id: 'n2h3',
      bg: 'cafe-dawn',
      lines: [
        say('yuki', 'あらすじ、ですか。', 'surprise'),
        say('yuki', '……えっと。眠れない女の子が、夜の街を歩く話で。'),
        say('yuki', 'それだけです。'),
        say('yuki', '……あれ。口にすると、すごく、短い。', 'shy'),
        say('yuki', 'なんで、三十二枚も書いたんだろう、これ。'),
        heart('（それは、たぶん、そういうことなのだと思う。）'),
        say('yuki', '……でも。', 'normal'),
        say('yuki', '「それだけ」って言われたのは、はじめてで。'),
        say('yuki', 'それだけの話だから、書きたかったんだ、って、いま、思いました。', 'smile'),
        say('yuki', '……ありがとう。また、来ます。'),
        jump('n2i'),
      ],
    },
    {
      id: 'n2i',
      bg: 'cafe-dawn',
      lines: [
        exit('yuki'),
        sfx('bell'),
        nar('窓の外で、雨が、少しだけ弱くなった。'),
        enter('garnet', 'right', 'smile'),
        say('garnet', 'おつかれさま。', 'smile'),
        say('garnet', '今日は、三組。よく回っていたわ。', 'normal'),
        say('garnet', '……この店の客は、みんな、何かを待ってるの。'),
        say('garnet', '返事だったり、朝だったり、自分の言葉だったり。'),
        say('garnet', 'あなたが淹れる一杯は、その、待っている時間の中身になる。'),
        say('garnet', '……重い?', 'smile'),
        heart('（重い、とは言わないことにする。）'),
        say('garnet', 'ふふ。いい返事。', 'smile'),
        chapterCard('第三章', '苦いものを'),
        jump('n3a'),
      ],
    },
  ],
};