import { profileOrder } from '../ingredients';
import type { Chapter } from '../types';
import {
  bg,
  branch,
  chapterCard,
  choice,
  enter,
  exit,
  heart,
  jump,
  nar,
  order,
  say,
  sfx,
  trustUp,
} from './helpers';

/**
 * プロローグ：最初の一杯
 *   街 → 店 → ガーネットの説明とチュートリアル → 最初の客ユキ → 夜明け
 */
export const PROLOGUE: Chapter = {
  id: 'prologue',
  title: 'プロローグ',
  subtitle: '最初の一杯',
  start: 'p0',
  scenes: [
    {
      id: 'p0',
      title: '午前零時',
      bg: 'street-rain',
      lines: [
        nar('午前零時を過ぎると、この街は少しだけ別の顔になる。'),
        nar('雨が路面を叩いて、ネオンの赤と青を水たまりに溶かしていく。'),
        nar('眠れない者たちが、眠らない街を歩いている。'),
        nar('路地の奥に、小さな灯り。'),
        nar('『CAFE NOCTURNAL』—— 夜だけ開く喫茶店。'),
        heart('…ここで合っているはずだ。'),
        nar('扉を押すと、乾いた音でベルが鳴った。'),
        sfx('bell'),
        bg('cafe-night'),
        nar('中は、思ったより静かだった。'),
        nar('琥珀色のランプ。磨かれたカウンター。棚いっぱいの瓶と缶。'),
        nar('そして、カウンターの向こうに立つ女がひとり。'),
        enter('garnet', 'center', 'smile'),
        say('garnet', 'いらっしゃい。', 'smile'),
        say('garnet', '…ああ、あなたが今日から働く子ね。'),
        say('garnet', '私はガーネット。この店の店主。'),
        say('garnet', 'ずぶ濡れじゃないの。タオル、そこにあるから使って。'),
        heart('（タオルは、温められていた。）'),
        say('garnet', 'ここは、真夜中から夜明けまでだけ開いてる喫茶店。'),
        say('garnet', '来るのは、だいたい——眠れない人たち。'),
        say('garnet', '人間も、人狼も、吸血鬼も、アンドロイドも、ね。'),
        say('garnet', '眠れない理由は、みんな違う。だから話も、みんな違う。', 'normal'),
        say('garnet', 'あなたの仕事は、その話を聴いて、一杯を作ること。'),
        say('garnet', 'それだけ。難しくないでしょう?', 'smile'),
        heart('（そう言う顔は、少しだけ「難しくないわけないでしょ」と言っていた。）'),
        say('garnet', 'ルールは三つ。'),
        say('garnet', 'ひとつ。客の話を、途中で切らないこと。'),
        say('garnet', 'ふたつ。飲み物は、必ず手で作ること。', 'normal'),
        say('garnet', 'みっつ。——この店では、誰も眠らなくていい。', 'smile'),
        say('garnet', 'さ、まずは腕を見せてよ。'),
        say('garnet', '温かくて、まろやかで、少し甘いもの。私に一杯。', 'smile'),
        jump('p1'),
      ],
    },
    {
      id: 'p1',
      title: '最初の一杯',
      bg: 'cafe-counter',
      lines: [
        heart('（ミルクをベースに、はちみつをひとさじ。温かい状態で。）'),
        order({
          order: profileOrder({
            id: 'p-tutorial',
            label: '温かくて、まろやかで、少し甘いもの',
            from: ['milk', 'honey'],
            temperature: 'hot',
          }),
          customer: 'garnet',
          hint: 'ミルク＋はちみつ／温かい。',
          results: { perfect: 'p2', good: 'p2', off: 'p1b' },
        }),
      ],
    },
    {
      id: 'p1b',
      bg: 'cafe-counter',
      lines: [
        say('garnet', 'ふふ。落ち着いて。もう一度だけ言うわね。', 'smile'),
        say('garnet', '「温かくて、まろやかで、少し甘いもの」。'),
        say('garnet', 'まろやかさなら、ミルク。甘さなら、はちみつかキャラメル。'),
        say('garnet', '温度は、右上のスイッチで変えてちょうだい。', 'normal'),
        jump('p1'),
      ],
    },
    {
      id: 'p2',
      bg: 'cafe-counter',
      lines: [
        enter('garnet', 'center', 'smile'),
        say('garnet', '……ん。'),
        say('garnet', 'うん。いい感じ。あなた、手つきが丁寧ね。', 'smile'),
        say('garnet', 'この仕事は、丁寧さがいちばん大事。才能より、ずっと。'),
        say('garnet', '今日の店は、あなたに任せても大丈夫そう。', 'normal'),
        say('garnet', 'ああ、そうだ。名前はなんて呼べばいい?'),
        say('garnet', '…{{name}}ね。覚えた。', 'smile'),
        sfx('bell'),
        say('garnet', 'おや。もう来たみたい。', 'normal'),
        nar('ベルの音が、雨の音に混ざる。'),
        nar('扉の向こう、白いものがふわりと揺れた。'),
        exit('garnet'),
        jump('p3'),
      ],
    },
    {
      id: 'p3',
      title: '最初の客',
      bg: 'cafe-night',
      lines: [
        nar('入ってきたのは、雪のような色をした女だった。'),
        nar('髪が、濡れていないのに、しっとりと光っている。'),
        enter('yuki', 'center', 'tired'),
        say('yuki', '……こんばんは。', 'tired'),
        say('yuki', 'あの、まだ、開いてますか。'),
        say('yuki', '……よかった。'),
        nar('彼女は、いちばん奥の、壁に向かった席を選んだ。'),
        nar('いつもの席、という選び方だった。'),
        say('yuki', 'えっと……飲み物、おまかせでもいいですか。', 'shy'),
        say('yuki', '甘いのは、いらない。あったかいのも、いまは、いや。'),
        say('yuki', '冷たくて、苦いもの。', 'normal'),
        say('yuki', '……苦い方が、頭が動くので。'),
        heart('（冷たくて、苦いもの。ベースはコーヒーだろう。）'),
        order({
          order: profileOrder({
            id: 'p-yuki-1',
            label: '冷たくて、苦いもの',
            from: ['coffee'],
            temperature: 'iced',
          }),
          customer: 'yuki',
          hint: 'ユキ：冷たいものと、強い苦味を好む。',
          results: { perfect: 'p4', good: 'p4', off: 'p3b' },
        }),
      ],
    },
    {
      id: 'p3b',
      bg: 'cafe-night',
      lines: [
        nar('カップを受け取った彼女は、一口飲んで、少しだけ目を細めた。'),
        say('yuki', '……あ、えっと。', 'shy'),
        say('yuki', '大丈夫です。わたし、こういうのも、好きなので。'),
        say('yuki', '……うそじゃないです。ほんとうに、好き嫌いが、あんまり無くて。', 'normal'),
        heart('（嘘ではなさそうだった。それだけに、少し悪いことをした。）'),
        trustUp('yuki', 0),
        jump('p4'),
      ],
    },
    {
      id: 'p4',
      bg: 'cafe-night',
      lines: [
        nar('彼女はカップを両手で包んで、しばらく黙っていた。'),
        nar('外はまだ雨。店の中は、雨の音がよく聴こえるくらいには静か。'),
        say('yuki', '……夜に、書いてるんです。', 'normal'),
        say('yuki', '小説を。'),
        say('yuki', '雪女って、寒いところの話ばかり書くと思われるんですけど。'),
        say('yuki', 'わたしが書きたいのは、もっと、べつのことなんです。', 'shy'),
        say('yuki', '夜の街とか。路地の灯りとか。眠らない誰かの話とか。'),
        say('yuki', '……でも、書いたものを人に読ませるのが、こわくて。'),
        nar('彼女はカップの底に、まだ残っている黒いものを揺らした。'),
        say('yuki', '苦いものは、好きです。'),
        say('yuki', '飲んでるあいだ、うまく言えないことを、言わなくていいので。', 'normal'),
        heart('（それは、この店の客みんなに言えることなのかもしれない。）'),
        choice(
          [
            {
              text: '「次に書いたら、聴かせてください」',
              set: (s) => {
                s.flags.promise_yuki = true;
                s.trust.yuki = (s.trust.yuki ?? 0) + 1;
              },
            },
            {
              text: '「ここでは、言わなくていいですよ」',
              set: (s) => {
                s.trust.yuki = (s.trust.yuki ?? 0) + 1;
              },
            },
          ],
          '何か、返す?',
        ),
        branch(
          (s) => Boolean(s.flags.promise_yuki),
          [
            say('yuki', '……っ。', 'surprise'),
            say('yuki', 'じゃあ、次に来たとき、持ってきます。', 'shy'),
            say('yuki', 'あ、あの、期待しないでください。ほんとに、まだ、うまくないので。'),
          ],
          [
            say('yuki', '……そう、ですか。', 'normal'),
            say('yuki', 'そういう店、はじめてです。', 'smile'),
            say('yuki', '……また、来ます。'),
          ],
        ),
        nar('彼女は、いちばん奥の席から立った。'),
        nar('出口の前で、一度だけ振り返る。'),
        say('yuki', '……ごちそうさまでした。'),
        exit('yuki'),
        sfx('bell'),
        jump('p5'),
      ],
    },
    {
      id: 'p5',
      bg: 'cafe-dawn',
      lines: [
        nar('窓の外が、濃い藍色から少しずつ薄くなっていく。'),
        enter('garnet', 'right', 'smile'),
        say('garnet', 'おつかれさま。初日、合格。', 'smile'),
        say('garnet', 'さっきの人、ユキさん。だいたい雨の日に来るわ。', 'normal'),
        say('garnet', 'そういえば、その……', 'smile'),
        say('garnet', '眠れないお客さんには、ひとつだけ、いいことがあるの。'),
        say('garnet', '眠らない夜は、長い。長い夜には、話す時間がある。'),
        say('garnet', '話したことは、だいたい、その人の味になる。'),
        say('garnet', 'だから、この店のメニューは、ずっと増えていくのよ。', 'smile'),
        heart('（棚の瓶は、たしかに、多すぎるくらいだった。）'),
        say('garnet', '夜が明けたら、店は閉める。'),
        say('garnet', 'また明日の零時にね。'),
        say('garnet', '——おやすみ。眠れないなら、またここへ。', 'smile'),
        nar('夜明け。街が、少しだけ眠る。'),
        chapterCard('第一章', '眠れない者たち'),
        jump('n1a'),
      ],
    },
  ],
};